(function() {var implementors = {};
implementors['tendril'] = ["impl&lt;F&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/collections/borrow/trait.Borrow.html' title='collections::borrow::Borrow'>Borrow</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.slice.html'>[<a href='http://doc.rust-lang.org/nightly/std/primitive.u8.html'>u8</a>]</a>&gt; for <a class='struct' href='tendril/struct.Tendril.html' title='tendril::Tendril'>Tendril</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='tendril/fmt/trait.SliceFormat.html' title='tendril::fmt::SliceFormat'>SliceFormat</a></span>",];implementors['string_cache'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/collections/borrow/trait.Borrow.html' title='collections::borrow::Borrow'>Borrow</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html' title='std::ffi::c_str::CStr'>CStr</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CString.html' title='std::ffi::c_str::CString'>CString</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/collections/borrow/trait.Borrow.html' title='collections::borrow::Borrow'>Borrow</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html' title='std::ffi::os_str::OsStr'>OsStr</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsString.html' title='std::ffi::os_str::OsString'>OsString</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/collections/borrow/trait.Borrow.html' title='collections::borrow::Borrow'>Borrow</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/path/struct.Path.html' title='std::path::Path'>Path</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html' title='std::path::PathBuf'>PathBuf</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
